service: lambda-email-failure-demo

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish # Keep the permission to publish to SNS
      Resource:
        - arn:aws:sns:${self:provider.region}:${aws:accountId}:EmailNotifications # Replace with your SNS topic ARN

functions:
  mainFunction:
    handler: handler.main
    maximumRetryAttempts: 0 # Set the desired maximum retries
    events:
      - http:
          path: run
          method: get
    onError: !Ref EmailNotificationTopic # Send error notifications to the SNS topic
    destinations:
      onFailure:
        type: sqs # Send failed messages to SQS
        arn: !GetAtt FailedMessageQueue.Arn # Reference to the SQS queue

resources:
  Resources:
    EmailNotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        Subscription:
          - Endpoint: meet.vaghasiya@simformsolutions.com
            Protocol: email
        TopicName: EmailNotifications

    FailedMessageQueue: # Define the SQS queue
      Type: AWS::SQS::Queue
      Properties:
        QueueName: MyFailedMessagesQueue

outputs:
  FailedMessageQueueArn:
    Value: !GetAtt FailedMessageQueue.Arn
  EmailNotificationTopicArn:
    Value: !Ref EmailNotificationTopic
