# serverless.yml
service: layer-demo

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
    layers:
      - { Ref: DateUtilsLambdaLayer }  # Reference the layer by its name

layers:
  dateUtils:
    path: layers/date-utils/
    name: dateUtils
    description: A simple utility for getting the current time
    compatibleRuntimes:
      - nodejs20.x
