service: s3-lambda-trigger

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

custom:
  # Define a unique bucket name based on the stage and region
  bucketName: my-upload-bucket-${opt:stage, 'dev'}  # Bucket name is based on the stage

functions:
  myFunction:
    handler: handler.myFunction  # Path to your Lambda function code
    memorySize: 256               # Adjust memory size as needed
    timeout: 30                   # Adjust timeout as needed
    description: 'My Lambda function triggered by S3 events'
    environment:
      BUCKET_NAME: ${self:custom.bucketName}  # Pass the bucket name to the function
    iamRoleStatements:            # IAM permissions for the Lambda function
      - Effect: "Allow"
        Action:
          - "s3:GetObject"
          - "s3:PutObject"
        Resource: 
          - !Sub 'arn:aws:s3:::${self:custom.bucketName}/*'
    events:
      - s3:
          bucket: ${self:custom.bucketName}  # Reference to the S3 bucket
          event: s3:ObjectCreated:*             # Trigger on all object creation events
          existing: true                        # Indicate that the bucket already exists

resources:
  Resources:
    MyUploadBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ${self:custom.bucketName}  # Set bucket name
