service: s3-lambda-trigger2

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: 
        - !Sub 'arn:aws:s3:::${self:custom.bucketName}/*'

custom:
  uniqueId: ${opt:uniqueId, 'random-'}${opt:timestamp, '290909013'}  # Unique identifier
  bucketName: my-upload-bucket-${opt:stage, 'dev'}-${self:custom.uniqueId}  # Updated unique bucket name
  build:
    packagerOptions:
      scripts:
        - npm install --os=linux --cpu=x64 sharp
functions:
  myFunction:
    handler: handler.myFunction
    memorySize: 256
    timeout: 30
    description: 'My Lambda function triggered by S3 events'
    environment:
      BUCKET_NAME: ${self:custom.bucketName}
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*