service: my-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  versionFunctions: true  # Automatically creates versions for Lambda functions
  logRetentionInDays: 7  # Set CloudWatch log retention
  tracing:
      apiGateway: true  # Enable X-Ray tracing for API Gateway (if used)
      lambda: true      # Enable X-Ray tracing for Lambda functions
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudwatch:PutMetricData"
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"
functions:
  myFunction:
    handler: handler.myFunction
    memorySize: 256
    timeout: 30
    description: 'My Lambda function description'
    environment:
      STAGE: ${opt:stage, 'dev'}
      LOG_LEVEL: ${opt:logLevel, 'info'}
    events:
      - http:
          path: invoke
          method: post
    tracing: Active

plugins:
  - serverless-aws-alias-v3 #actual library name is serverless-aws-alias. but it has some error, so this package is wrapper of that with resolved error

#https://www.serverless.com/plugins/serverless-aws-alias#installation

